
name: Python Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build
        run: |
          if [ -f pyproject.toml ]; then
            pip install build && python -m build
          elif [ -f setup.py ]; then
            pip install wheel && python setup.py sdist bdist_wheel
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
    