name: Python Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint with flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      # Test with pytest
      - name: Test with pytest
        run: |
          pip install pytest
          pytest .

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t python-hello-world .
        env:
          DOCKER_BUILDKIT: 1

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image
      - name: Push Docker image
        run: |
          docker tag python-hello-world ${{ secrets.DOCKER_USERNAME }}/python-hello-world
          docker push ${{ secrets.DOCKER_USERNAME }}/python-hello-world
