name: Python Hello World Workflow

on:
  push:\    branches: [ main ]
  pull_request:\    branches: [ main ]

jobs:
  build:\    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
      - name: Test with unittest
        run: |
          pip install unittest
          python -m unittest discover -s . -p 'test_*.py'
  deploy:\    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Packages
        uses: actions/authorize@v1
        with:
          full-name: ${{ github.actor }}
          repository: ${{ github.repository }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/python-hello-world:${GITHUB_SHA}
  test:\    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest .