# Define the workflow name
name: Python Package

# Define the triggers for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the job
jobs:
  build:

    # Define the runner environment
    runs-on: ubuntu-latest

    # Define the steps for the job
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Setup Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint and test
      - name: Lint and test
        run: |
          pip install flake8
          flake8 .
          python -m unittest discover -s .

      # Build and package
      - name: Build and package
        run: |
          docker build -t python-hello-world .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t atharrvv/python-hello-world .
          docker tag python-hello-world:latest atharrvv/python-hello-world:latest
          docker push atharrvv/python-hello-world:latest

      # Deploy
      - name: Deploy
        run: |
          # Deployment steps (e.g., to a cloud platform)
          echo "Deploying to cloud platform..."
