name: Test Workflow
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover -s python_hello_world/tests
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: python_hello_world/tests/test_results.xml
      - name: Report test results
        run: |
          xunit2junit -f junit_xml test-results/xml test-results/junit.xml
          upload-artifact test-results/junit.xml